### ISSUE TITLE
Please check error

### ISSUE THREAD

**Issue by modbender** [pirate/django-http2-middleware#1]
In middleware line 122, please change `if getattr(request, 'to_preload'):` to `if hasattr(request, 'to_preload'):`

**Comment by fdemmer** [comment]
why? that would not consider the _value_ of `to_preload` at all.

probably better to do `if getattr(request, 'to_preload', None):` to avoid an exception if the attribute is not on `request` and still use its value in the if-statement.

**Comment by modbender** [comment]
Yes as you said it produces an exception. And also, for an if statement here, you won't need to consider the value of to_preload, because either to_preload variable is attached to the request object if not it doesn't exist.  If request does have to_preload variable, then it automatically is not empty because of https://github.com/pirate/django-http2-middleware/blob/f5578c6474bf2a45f80640b15b967e775011ef5d/middleware.py#L37

And also, in **this case** getattr(request, 'to_preload', None) is same as hasattr(request, 'to_preload').

**Comment by pirate** [comment]
The original design was intentional, I don't want it to attach preload headers if the value of `to_preload` is falsy. There are other layers of the stack that can set the `request.to_preload` attr, the one you linked to is only one example.
